// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShipmentAPI.EfCore;

#nullable disable

namespace shipmentAPI.Migrations
{
    [DbContext(typeof(EF_DataContext))]
    [Migration("20221123113948_setDataBase")]
    partial class setDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShipmentApi.Model.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("dimentions_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("weight_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Carrier");
                });

            modelBuilder.Entity("ShipmentApi.Model.CarrierService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrierId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CarrierService");
                });

            modelBuilder.Entity("ShipmentApi.Model.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrierId")
                        .HasColumnType("integer");

                    b.Property<int>("CarrierServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("height")
                        .HasColumnType("integer");

                    b.Property<int>("weight")
                        .HasColumnType("integer");

                    b.Property<int>("width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("CarrierServiceId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("ShipmentApi.Model.CarrierService", b =>
                {
                    b.HasOne("ShipmentApi.Model.Carrier", null)
                        .WithMany("CarrierServices")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShipmentApi.Model.Shipment", b =>
                {
                    b.HasOne("ShipmentApi.Model.Carrier", "Carrier")
                        .WithMany("Shipments")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipmentApi.Model.CarrierService", "CarrierService")
                        .WithMany("Shipments")
                        .HasForeignKey("CarrierServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");

                    b.Navigation("CarrierService");
                });

            modelBuilder.Entity("ShipmentApi.Model.Carrier", b =>
                {
                    b.Navigation("CarrierServices");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("ShipmentApi.Model.CarrierService", b =>
                {
                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
